### ISSUE TITLE
Licensing chekck up

### ISSUE THREAD

**Issue by bartossh** [pirateup/tasks#36]
Check licensing and legal case of use frameworks that are proposed to be used to build our application with. 
I propose to collect data and do the review meeting.

Task is divided for each team member as fallows:  
- 4fuss = back end python frameworks and database 
- wojtek = ask 4fuss for task regarding to back end

- allgreed = front end vue + vuex + testin
- bartoshko = ask allgreed for tasks regarding to this research

**Comment by allgreed** [comment]
Here's a license check for front.
Right now, we're running 4 dependencies on MIT license

https://github.com/vuejs/vue
https://github.com/vuejs/vuex
https://github.com/vuejs/vue-router
https://github.com/mzabriskie/axios

And 1 dependency without a license:

https://github.com/xkjyeah/vue-google-maps (we're using this fork)
https://github.com/GuillaumeLeclerc/vue-google-maps (original, lacking the license)

JEST:
https://github.com/facebook/jest/blob/master/PATENTS -> same as React, so it's a no-go.

GraphQL js client:
https://github.com/graphql/graphql-js/blob/master/PATENTS -> again, no-go.

The standard itself requires a check:
https://facebook.github.io/graphql/

@Bartoshko ?

**Comment by allgreed** [comment]
We're also runnning regenerator-transform and regenerator-runtime sub-dependency with Facebook patent clause.

**Comment by 4fuss** [comment]
Server side tools:

- PostgreSQL is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT
- PostGIS is released under the GNU General Public License (GPLv2 or later)
- Flask is licensed under a three clause BSD License
- Flask-SQLAlchemy same as Flask
- GeoAlchemy2: MIT License
- psycopg2: LGPL
- requests: Apache2 License

**Comment by allgreed** [comment]
@Bartoshko How about splitting this to front and back? ;)

**Comment by allgreed** [comment]
Created #39 
We're done here ^^
